name: Update tree

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 5 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    # The type of runner that the job will run on
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
         activate-environment: usher
         python-version: 3.9
         channels: conda-forge,bioconda
      - run: |
          conda info
          conda list
          conda install usher
          pip install treeswift
  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: matUtils
        run: matUtils version

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          wget -qN https://github.com/theosanderson/taxonium/blob/master/taxoniumtools/test_data/tfci.pb
          python treeshears.py -i tfci.pb -o tfci2.pb
          
